name = "bevy_midi"
description = "Send and receive MIDI data to and from bevy using DAWS or MIDI Controllers"
link = "https://github.com/BlackPhlox/bevy_midi"
image = "bevy_midi_logo.png"
crate = "bevy_midi"
