name = "Bevy Input Mapper Plugin"
description = "An user-friendly input binding plugin with scenario profiles in mind."
link = "https://github.com/atahabaki/bevy_input_mapper"
crate = "bevy_input_mapper"
