name = "bevy_input_prompts"
description = "Mappings from bevy input types to popular input prompt asset paths."
link = "https://github.com/jonathandw743/bevy_input_prompts"
image = "bevy_input_prompts.png"
crate = "bevy_input_prompts"