name = "bevy_ineffable"
description = "A simple-to-use input manager for bevy that empowers players and makes accessibility easy."
link = "https://github.com/Jazarro/bevy_ineffable"
crate = "bevy_ineffable"
