name = "Virtual Joystick"
description = "Create and use a Virtual Joystick in a UI for bevy"
link = "https://github.com/SergioRibera/virtual_joystick"
image = "virtual_joystick.gif"
crate = "virtual_joystick"
