name = "bevy_third_person_camera"
description = "A simple, plug & play third person camera for bevy."
link = "https://crates.io/crates/bevy_third_person_camera"
image = "bevy_third_person_camera.gif"
crate = "bevy_third_person_camera"
