name = "bevy_networking_turbulence"
description = "Networking plugin running on naia-socket and turbulence libraries."
link = "https://github.com/smokku/bevy_networking_turbulence"
crate = "bevy_networking_turbulence"
