name = "bevy_rtc"
description = "A simple, multi-platform WebRTC networking library for client<->server topologies."
link = "https://github.com/loopystudios/bevy_rtc"
image = "bevy_rtc.png"
crate = "bevy_rtc"
