name = "bevy_eventwork_mod_websockets"
description = "A websocket transport layer for bevy_eventwork that supports WASM and Native."
link = "https://crates.io/crates/bevy_eventwork_mod_websockets"
crate = "bevy_eventwork_mod_websockets"
