# Name of your asset.
name = "bevy_mqtt"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A mqtt client Plugin for Bevy"

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/foxzool/bevy_mqtt"
