name = "bevy_renet2"
description = "Bevy Plugin for renet2, a cross-platform network library for Server/Client with authentication and client management"
link = "https://github.com/UkoeHB/renet2/tree/main/bevy_renet2"
