name = "bevy_prototype_simple_net"
description = "A working prototype networking plugin that can create client/server systems over TCP or UDP."
link = "https://github.com/0x22fe/bevy_prototype_simple_net"
# TODO: No crate.
