name = "bevy_ascii_terminal"
description = "A simple and fast solution for rendering ascii characters in a grid."
link = "https://github.com/sarkahn/bevy_ascii_terminal"
image = "bevy_ascii_terminal.gif"
crate = "bevy_ascii_terminal"
