name = "bevy_prototype_lyon"
description = "Draw fancy 2D shapes like outlined polygons, lines with caps, or SVG paths."
link = "https://crates.io/crates/bevy_prototype_lyon"
crate = "bevy_prototype_lyon"
