name = "bevy_ghx_proc_gen"
description = "2D & 3D procedural generation with WFC/Model synthesis"
link = "https://github.com/Henauxg/ghx_proc_gen"
image = "bevy_ghx_proc_gen.webp"
crate = "bevy_ghx_proc_gen"
