name = "bevy_mod_raycast"
description = "A plugin for raycasting against meshes and primitives"
link = "https://github.com/aevyrie/bevy_mod_raycast"
image = "bevy_mod_raycast.png"
crate = "bevy_mod_raycast"
