name = "bevy_aabb_instancing"
description = "Render millions of axis-aligned boxes"
link = "https://github.com/ForesightMiningSoftwareCorporation/bevy-aabb-instancing"
image = "bevy_aabb_instancing.png"
crate = "bevy-aabb-instancing"
