# Name of your asset.
name = "bevy_aabb_instancing"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "Render millions of axis-aligned boxes"

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/ForesightMiningSoftwareCorporation/bevy-aabb-instancing"

# Optional image to showcase your asset. Should be a png/jpg/gif located next to your toml file.
image = "bevy_aabb_instancing.png"