name = "bevy_mod_scripting"
description = "Multi-language scripting support for Bevy"
link = "https://github.com/makspll/bevy_mod_scripting"
image = "bevy_mod_scripting_logo.png"
crate = "bevy_mod_scripting"
