name = "bevy-add-events-macro"
description = "adds the add_events! macro to make adding multiple events easier"
link = "https://crates.io/crates/bevy-add-events-macro"
crate = "bevy-add-events-macro"
