name = "bevy_window_utils"
description = "Bevy window utilities such as setting up window icons and taskbar progress."
link = "https://github.com/shwwwa/bevy_window_utils"
image = "bevy_window_utils.png"
crate = "bevy_window_utils"
