name = "bevy-panic-handler"
description = "A bevy plugin that creates a popup and logs to error on panic. "
link = "https://github.com/Koranir/bevy-panic-handler"
image = "bevy-panic-handler.png"
crate = "bevy-panic-handler"
