name = "bevy_shuffle_bag"
description = "A tiny crate providing a collection hat can endlessly be picked in a random, nonrepeating order."
link = "https://github.com/janhohenheim/bevy_shuffle_bag"
crate = "bevy_shuffle_bag"
