name = "Bevy Generative Grammars"
description = "A library providing helpers for Generative Grammars, as well as a Tracery implementation."
link = "https://github.com/lee-orr/bevy-generative-grammars"
crate = "bevy_generative_grammars"
