# Name of your asset.
name = "Bevy Generative Grammars"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A library providing helpers for Generative Grammars, as well as a Tracery implementation."

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/lee-orr/bevy-generative-grammars"

