# Formerly bevy_loading
name = "iyes_progress"
description = "Easily implement a loading state, tracking the progress of assets and other tasks."
link = "https://crates.io/crates/iyes_progress"
crate = "iyes_progress"
