name = "Bevy Blur Regions"
description = "Selectively blur regions of the screen to create glassy UI elements"
link = "https://github.com/atbentley/bevy_blur_regions"
image = "bevy_blur_regions.png"
crate = "bevy_blur_regions"
