name = "bevy_ui_exact_image"
description = "Bevy UI image widget that provides exact control over image sizes and supports rotations."
link = "https://github.com/ickshonpe/bevy_ui_exact_image"
crate = "bevy_ui_exact_image"
