name = "bevy_ninepatch"
description = "Display 9-Patch UI elements, where you can specify how different parts of a PNG should grow"
link = "https://crates.io/crates/bevy_ninepatch"
image = "bevy_ninepatch.png"
