name = "bevy_ratatui_render"
description = "A plugin for rendering your bevy app to the terminal using ratatui."
link = "https://github.com/cxreiff/bevy_ratatui_render"
image = "bevy_ratatui_render.gif"
crate = "bevy_ratatui_render"
