name = "bevy_cosmic_edit"
description = "Provides multiline text editing for bevy apps"
link = "https://github.com/Dimchikkk/bevy_cosmic_edit"
image = "bevy_cosmic_edit.gif"
crate = "bevy_cosmic_edit"
