name = "Bevy SplashScreen"
description = "A plugin for bevy that allows you to create screens to display brands and development teams"
link = "https://github.com/SergioRibera/bevy_splash_screen"
image = "bevy_splash_screen.gif"
crate = "bevy_splash_screen"
