name = "Bevy SplashScreen"
description = "A plugin for bevy which allows you to create screens to show the brands and development teams behind your amazing game"
link = "https://github.com/SergioRibera/bevy_splash_screen"
image = "bevy_splash_screen.gif"
