name = "bevy_quickmenu"
description = "A simple-to-use nested menu system for BevyUI which supports gamepad, keyboard or mouse navigation"
link = "https://crates.io/crates/bevy_quickmenu"
image = "bevy_quickmenu.gif"
crate = "bevy_quickmenu"
