# Name of your asset.
name = "Bevy Discord"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A Discord Plugin for Bevy"

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/as1100k/bevy-discord"

# Optional image to showcase your asset.
# Should be a png/jpg/gif/webp located next to your toml file, less than 2 MB in size.
# We recommend using a 16:9 aspect ratio with a maximum width of 600 pixels.
# image = "my_plugin_icon.png"

# Optional crate name on crates.io. If there's more than one crate, pick any one of them.
crate = "bevy_discord"
