# Name of your asset.
name = "Tetris for Bevy 0.6 / 0.7"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A partial Tetris clone written as an introductory tutorial for Bevy 0.6 / 0.7"

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/langp11/bevy-tetris-0.6"

# Optional image to showcase your asset. Should be a png/jpg/gif located next to your toml file.
image = "bevy-tetris-0.6.png"
