name = "Digital Extinction"
description = "A free and modern RTS game, unconstrained by commercial requirements, legacy HW and old technology."
link = "https://github.com/DigitalExtinction/Game"
image = "digital-extinction.png"
