# Name of your asset.
name = "Game Of Life"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "A deadly simple game-of-life implementation in bevy engine."

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/rhapsodyn/bevy-game-of-life"

# Optional image to showcase your asset.
# Should be a png/jpg/gif/webp located next to your toml file, less than 2 MB in size.
image = "game-of-life.png"
