name = "Rock Run Rose's Odyssey"
description = "An 'Educational' Platformer for Kids to Learn Math and Reading—and Bevy for the Devs"
link = "https://github.com/uggla/rock_run"
image = "rock_run.png"
