name = "taipo"
description = "A Japanese language practice tool with an English mode. Type words to build towers and defend the station!"
link = "https://github.com/rparrett/taipo"
image = "taipo.gif"
