name = "bevy_spritesheet_animation"
description = "A Bevy plugin for animating sprites that are backed by spritesheets"
link = "https://github.com/merwaaan/bevy_spritesheet_animation"
image = "bevy_spritesheet_animation.gif"