name = "bevy_easy_gif"
description = "A 0-work 0-pain way to display GIF files in your Bevy games."
link = "https://crates.io/crates/bevy_easy_gif"
image = "bevy_easy_gif.gif"
crate = "bevy_easy_gif"
