name = "bevy_asepritesheet"
description = "Use animated Aseprite JSON sprite sheets in bevy game engine"
link = "https://crates.io/crates/bevy_asepritesheet"
image = "bevy_asepritesheet.gif"
crate = "bevy_asepritesheet"
