name = "bevy_github_ci_template"
description = "A simple template providing basic CI and automated builds for Windows, Linux, MacOS and the web."
link = "https://github.com/bevyengine/bevy_github_ci_template"
