name = "Foxtrot"
description = "The all-in-one 3D game template supporting a list of common game features and helper crates."
link = "https://github.com/janhohenheim/foxtrot"
image = "foxtrot.webp"
crate = "foxtrot"
