name = "bevy_gltf_components"
description = "Define components directly inside gltf files (from Blender & co) and instanciate the components on the Bevy side."
link = "https://crates.io/crates/bevy_gltf_components"
