name = "bevy-remote-devtools"
description = "UI for debugging entities, assets, logs and systems over network"
link = "https://github.com/reneeichhorn/bevy-remote-devtools"
crate = "bevy-remote-devtools-plugin"
