name = "bevy_dev_console"
description = "Source-like developer console with a powerful command language"
link = "https://github.com/doonv/bevy_dev_console"
image = "bevy_dev_console.png"
crate = "bevy_dev_console"
