name = "skein"
description = "Insert component data in Blender; export data with glTF; Components are instantiated when spawning Scenes."
link = "https://github.com/rust-adventure/skein"
image = "skein.png"
crate = "bevy_skein"
