name = "bevy-persistent-windows"
description = "A Bevy plugin to easily create and manage windows that remember where they were."
link = "https://crates.io/crates/bevy-persistent-windows"
crate = "bevy-persistent-windows"
