name = "Bevy Heterogenous Texture Atlas Loader"
description = "Load heterogenous texture atlases from a ron manifest"
link = "https://github.com/ickshonpe/bevy_heterogeneous_texture_atlas_loader"
crate = "bevy_heterogeneous_texture_atlas_loader"
