name = "bevy_embedded_assets"
description = "Plugin to embed assets in your game binary"
link = "https://crates.io/crates/bevy_embedded_assets"
image = "bevy_embedded_assets.png"
crate = "bevy_embedded_assets"
