# Name of your asset.
name = "bevior_tree"

# Description of your asset. It should be less than 100 characters and not contain formatting.
description = "Behavior tree plugin."

# Where can your asset be found. It can be a link to crates.io, github, gitlab or similar.
link = "https://github.com/hyranno/bevior_tree"
