name = "bevy_openai"
description = "An event-driven plugin for Bevy that provides convenient access to the OpenAI API."
link = "https://github.com/hytracen/bevy_openai"
image = "bevy_openai.png"
crate = "bevy_openai"
