name = "bevy_rerecast"
description = "Port of Recast, the industry-standard navigation mesh generator used by Unreal, Unity, Godot, and other game engines."
link = "https://github.com/janhohenheim/rerecast"
crate = "bevy_rerecast"
image = "rerecast.jpg"
