name = "Understanding Dynamic Queries in bevy 0.11"
description = "Explains roughly how queries work and how they can be improved with dynamic queries"
link = "https://github.com/bevyengine/bevy/discussions/9816"
